fixed antisense bug

diff --git a/bin/snapt b/bin/snapt
--- a/bin/snapt
+++ b/bin/snapt
@@ -22,9 +22,10 @@ echo snapt ${@}
 
 help_message () {
 	echo ""
-	echo "Usage: SnapT [options] -1 reads_1.fastq -2 reads_2.fastq -g genome.fa -o output_dir"
+	echo "Example usage: "
+	echo "snapt -1 reads_1.fastq -2 reads_2.fastq -g genome.fa -a genome.gff -o output_dir -d nr.dmnd -t 24 -l 3000"
 	echo ""
-	echo "SnapT options:"
+	echo "SnapT core options:"
 	echo "	-1 STR		forward transcriptome (or metatranscriptome) reads"
 	echo "	-2 SRT		reverse transcriptome (or metatranscriptome) reads (optional)"
 	echo "	-g STR		genome (or metagenome) fasta file"
@@ -34,11 +35,11 @@ help_message () {
 	echo "	-t INT		number of threads (default=1)"
 	echo "	-d STR		nr protein database DIAMOND .dmnd index (see installation instructions for details)"
 	echo ""
-	echo "Aligment options:"
+	echo "Additional options:"
 	echo "	-r STR		rna-strandness: R or F for single-end, RF or FR for paired-end (default=FR)"
 	echo "	-I INT		min insert size (default=$MIN_INSERT_VALUE)"
 	echo "	-X INT		max insert size (default=$MAX_INSERT_VALUE)"
-	echo "	-m INT		gap distance to close transcripts (default=$GAP_VALUE)"
+	echo "	-m INT		minimum sRNA size during assembly (default=$GAP_VALUE)"
 	echo ""
 	echo "	--version | -v	show current SnapT version"
 	echo "";}
@@ -227,26 +228,28 @@ else
 	prodigal -i $GENOME -f gff -o ${OUT}/transcript_assembly/prodigal_orfs.gff -q
 	if [[ $? -ne 0 ]]; then error "PRODIGAL failed to annotate genome. Exiting..."; fi
 fi
-
-
 ORFS=${OUT}/transcript_assembly/prodigal_orfs.gff
 
-comm "Intersecting the transcripts with the ORFs found with Prodigal to remove transcripts that are from coding regions"
-snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.gff
-if [[ ! -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then error "Could not intersect the transcripts with the ORFs. Exiting..."; fi
-comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
+if [[ -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then
+	comm "Looks like intersecting the transcripts with the annotation and ORFs was already done. Skipping..."
+else
+	comm "Intersecting the transcripts with the ORFs found with Prodigal to remove transcripts that are from coding regions"
+	snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then error "Could not intersect the transcripts with the ORFs. Exiting..."; fi
+	comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
 
-comm "Intersecting the transcripts with the provided annotation in $ANNOTATION"
-snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.anno.gff
-if [[ ! -s ${OUT}/transcript_assembly/ncRNA.anno.gff ]]; then error "Could not intersect the transcripts with the provided annotation. Exiting..."; fi
-comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
+	comm "Intersecting the transcripts with the provided annotation in $ANNOTATION"
+	snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.anno.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.anno.gff ]]; then error "Could not intersect the transcripts with the provided annotation. Exiting..."; fi
+	comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
 
-comm "Consolidating intergenic and antisense transcripts predicted from ORFs and $ANNOTATION"
-mv ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/transcript_assembly/ncRNA.orf.gff
-snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}/transcript_assembly/ncRNA.anno.gff > ${OUT}/transcript_assembly/ncRNA.gff
-if [[ ! -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then error "Transcript consolidation failed. Exiting..."; fi
+	comm "Consolidating intergenic and antisense transcripts predicted from ORFs and $ANNOTATION"
+	mv ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/transcript_assembly/ncRNA.orf.gff
+	snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}/transcript_assembly/ncRNA.anno.gff > ${OUT}/transcript_assembly/ncRNA.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then error "Transcript consolidation failed. Exiting..."; fi
+fi
+
 comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts"
-
 cp ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/nc_rna.gff
 
 
@@ -255,17 +258,22 @@ cp ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/nc_rna.gff
 ########################################################################################################
 announcement "CURATE NON_CODING TRANSCRIPTS"
 
-mkdir ${OUT}/srna_curation
-mv ${OUT}/nc_rna.gff ${OUT}/srna_curation/raw_nc_transcripts.gff
+if [[ -s ${OUT}/srna_curation/small_nc_transcripts.gff ]]; then
+	comm "Looks like non-coding transcript curation was already done. Skipping..."
+else
+	mkdir ${OUT}/srna_curation
+	mv ${OUT}/nc_rna.gff ${OUT}/srna_curation/raw_nc_transcripts.gff
 
-comm "dynamically thresholding transcripts that are too close to a contig's edge"
-snapt_positional_curation.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
-if [[ $? -ne 0 ]]; then error "Failed to remove transcripts close to contig edges. Exiting..."; fi
+	comm "dynamically thresholding transcripts that are too close to a contig's edge"
+	snapt_positional_curation.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
+	if [[ $? -ne 0 ]]; then error "Failed to remove transcripts close to contig edges. Exiting..."; fi
 
-comm "curating ncRNA predictions by size (minimum 50bp, maximum 500bp)"
-snapt_size_select.py ${OUT}/srna_curation/good_nc_transcripts.gff 50 500 > ${OUT}/srna_curation/small_nc_transcripts.gff 
+	comm "curating ncRNA predictions by size (minimum 50bp, maximum 500bp)"
+	snapt_size_select.py ${OUT}/srna_curation/good_nc_transcripts.gff 50 500 > ${OUT}/srna_curation/small_nc_transcripts.gff 
+	if [[ $? -ne 0 ]]; then error "Failed to size select the transcripts. Exiting..."; fi
+fi
+
 cp ${OUT}/srna_curation/small_nc_transcripts.gff ${OUT}/small_nc_transcripts.gff
-if [[ $? -ne 0 ]]; then error "Failed to size select the transcripts. Exiting..."; fi
 comm "Out of $(cat ${OUT}/srna_curation/good_nc_transcripts.gff | wc -l) ncRNAs, there are $(cat ${OUT}/small_nc_transcripts.gff | wc -l) small ncRNAs, of which $(cat ${OUT}/small_nc_transcripts.gff | grep "intergenic" | wc -l) are intergenic and $(cat ${OUT}/small_nc_transcripts.gff | grep "antisense" | wc -l) are antisense."
 
 
@@ -330,16 +338,18 @@ comm "pulling out small ncRNA preditions without any blastx hits to the NR datab
 snapt_filter_by_blastx.py ${OUT}/blastx_search/signifficant_hits.list ${OUT}/small_nc_transcripts.gff > ${OUT}/blastx_search/final_small_nc_transcripts.gff
 if [[ $? -ne 0 ]]; then error "Failed to filter out small ncRNAs without Blastx hits. Exiting..."; fi
 
-comm "cleaning up and pulling out fasta sequences of small ncRNAs"
+comm "cleaning up"
 mv ${OUT}/small_nc_transcripts.* ${OUT}/blastx_search
 cp ${OUT}/blastx_search/final_small_nc_transcripts.gff ${OUT}/small_ncRNAs.gff
+
+comm "pulling out fasta sequences of small ncRNAs"
 grep "antisense transcript" ${OUT}/small_ncRNAs.gff > ${OUT}/small_antisense_ncRNAs.gff
 grep "intergenic transcript" ${OUT}/small_ncRNAs.gff > ${OUT}/small_intergenic_ncRNAs.gff
-snapt_tpm_curve.py ${OUT}/small_ncRNAs.gff ${OUT}/small_antisense_ncRNAs.gff ${OUT}/small_intergenic_ncRNAs.gff ${OUT}/expression_curve.png
-
 bedtools getfasta -s -fi ${OUT}/hisat2_alignment/genome.fa -bed ${OUT}/small_antisense_ncRNAs.gff > ${OUT}/small_antisense_ncRNAs.fa
 bedtools getfasta -s -fi ${OUT}/hisat2_alignment/genome.fa -bed ${OUT}/small_intergenic_ncRNAs.gff > ${OUT}/small_intergenic_ncRNAs.fa
 
+comm "plotting small ncRNA TMP values for minimum expression cut-off evaluation"
+snapt_tpm_curve.py ${OUT}/small_ncRNAs.gff ${OUT}/small_antisense_ncRNAs.gff ${OUT}/small_intergenic_ncRNAs.gff ${OUT}/expression_curve.png
 
 ########################################################################################################
 ########################     sRNA DISCOVERY PIPELINE SUCCESSFULLY FINISHED!!!   ########################
