adding filtering steps

diff --git a/bin/snapt b/bin/snapt
--- a/bin/snapt
+++ b/bin/snapt
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
-VERSION="0.1"
+#SBATCH
+#SBATCH --job-name=metaWRAP
+#SBATCH --partition=lrgmem
+#SBATCH --time=72:0:0
+#SBATCH --nodes=1
+#SBATCH --ntasks-per-node=48
+#SBATCH --cpus-per-task=1
+#SBATCH --mem=800G
+
+
+VERSION="0.1.1"
+echo snapt ${@}
 
 ##############################################################################################################################################################
 # SnapT: Small ncRNA annotation pipeline for transcriptomic data
@@ -17,11 +28,12 @@ help_message () {
 	echo "	-1 STR		forward transcriptome (or metatranscriptome) reads"
 	echo "	-2 SRT		reverse transcriptome (or metatranscriptome) reads (optional)"
 	echo "	-g STR		genome (or metagenome) fasta file"
-	echo "	-a STR		genome (or metagenome) annotation gtf file (optional)"
+	echo "	-a STR		genome (or metagenome) annotation gtf/gff file (optional, but recommended)"
+	echo "	-l INT		minimum contig length (default=1000) for ncRNA annotation"
 	echo "	-o STR          output directory"
+	echo "	-t INT		number of threads (default=1)"
 	echo ""
 	echo "Aligment options:"
-	echo "	-t INT          number of threads (default=1)"
 	echo "	-r STR		rna-strandness: R or F for single-end, RF or FR for paired-end (default=FR)"
 	echo "	-I INT		min insert size (default=$MIN_INSERT_VALUE)"
 	echo "	-X INT		max insert size (default=$MAX_INSERT_VALUE)"
@@ -32,16 +44,14 @@ help_message () {
 
 
 
-comm () { ${SOFT}/print_comment.py "$1" "-"; }
-error () { ${SOFT}/print_comment.py "$1" "*"; exit 1; }
-warning () { ${SOFT}/print_comment.py "$1" "*"; }
-announcement () { ${SOFT}/print_comment.py "$1" "#"; }
+comm () { snapt_print_comment.py "$1" "-"; }
+error () { snapt_print_comment.py "$1" "*"; exit 1; }
+warning () { snapt_print_comment.py "$1" "*"; }
+announcement () { snapt_print_comment.py "$1" "#"; }
 
 # loading supplementary scripts
-SNAPT_PATH=$(which snapt.sh)
+SNAPT_PATH=$(which snapt)
 BIN_PATH=${SNAPT_PATH%/*}
-SOFT=${BIN_PATH}/snapt-scripts
-
 
 
 ########################################################################################################
@@ -55,6 +65,7 @@ MIN_INSERT_VALUE=0
 MAX_INSERT_VALUE=500
 GAP_VALUE=50
 THREADS=1
+LENGTH=1000
 
 OUT=none
 READS1=none
@@ -64,7 +75,7 @@ ANNOTATION=none
 
 
 # load in params
-OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m --long help,version -- "$@"`
+OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m:l: --long help,version -- "$@"`
 # make sure the params are entered correctly
 if [ $? -ne 0 ]; then help_message; exit 1; fi
 
@@ -77,6 +88,7 @@ while true; do
 		-g) GENOME=$2; shift 2;;
 		-a) ANNOTATION=$2; shift 2;;
 		-t) THREADS=$2; shift 2;;
+		-l) LENGTH=$2; shift 2;;
 		-r) STRAND_MAP_VALUE=$2; shift 2;;
 		-I) MIN_INSERT_VALUE=$2; shift 2;;
 		-X) MAX_INSERT_VALUE=$2; shift 2;;
@@ -101,11 +113,6 @@ elif [ ! -s $READS1 ]; then
 	error "Read file $READS1 does not exist, or is empty. Exiting."
 elif [ ! -s $GENOME ]; then
 	error "Genome/metagenome file $GENOME does not exist, or is empty. Exiting."
-fi
-
-# Check for correctly configured snapt-scripts folder
-if [ ! -s $SOFT/print_comment.py ]; then
-	error "The folder $SOFT does not exist or is not configured. Please make sure that the snapt-scripts folder is in the same directory as snapt.sh"
 fi
 
 announcement "BEGIN PIPELINE!"
@@ -165,19 +172,36 @@ else
 	if [[ $? -ne 0 ]]; then error "Samtools indexing failed. Exiting..."; fi
 fi
 
+
 ########################################################################################################
-########################              ASSEMBLE DE-NOVO TRANSCRIPTS              ########################
+########################                  ASSEMBLE TRANSCRIPTS                  ########################
 ########################################################################################################
-announcement "ASSEMBLE DE-NOVO TRANSCRIPTS"
+announcement "ASSEMBLE TRANSCRIPTS"
+
+if [[ $ANNOTATION == none ]]; then
+	comm "Genome annotation not provided. Using Prokka for annotation instead."
+	if [[ -s ${OUT}/prokka_annotation/genome.gff ]]; then
+		comm "Looks like the Prokka output already exists in the output directory. Skipping..."
+		ANNOTATION=${OUT}/prokka_annotation/genome.gff
+	else
+		comm "Running Prokka on $GENOME. This usually takes a few minutes for single genomes and a few hours for metagenomes."
+		prokka --quiet --cpus $THREADS --outdir ${OUT}/prokka_annotation --prefix genome --force $GENOME
+		if [[ $? -ne 0 ]]; then error "Prokka annotation failed. Exiting..."; fi
+		ANNOTATION=${OUT}/prokka_annotation/genome.gff
+	fi
+else
+	comm "Using $ANNOTATION annotation to guide Stringtie"
+fi
+
 
 mkdir ${OUT}/transcript_assembly
 if [[ -s ${OUT}/transcript_assembly/raw_transcripts.gff ]]; then
 	comm "Looks like the stringtie assembly already exists in the output directory. Skipping..."
 else
-	comm "Building de-novo transcripts and transcriptome expression file"
+	comm "Building reference-based transcripts and transcriptome expression file"
 	stringtie ${OUT}/hisat2/alignment.bam \
 		-o ${OUT}/transcript_assembly/raw_transcripts.gff \
-		-p $THREADS -m $GAP_VALUE
+		-p $THREADS -m $GAP_VALUE -G $ANNOTATION
 	if [[ $? -ne 0 ]]; then error "Stringtie transcript assembly failed. Exiting..."; fi
 fi
 
@@ -198,19 +222,21 @@ fi
 ORFS=${OUT}/transcript_assembly/prodigal_orfs.gff
 
 comm "Intersecting the transcripts with the ORFs found with Prodigal to remove transcripts that are from coding regions"
-${SOFT}/intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.gff
+snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.gff
 if [[ $? -ne 0 ]]; then error "Could not intersect the transcripts with the ORFs. Exiting..."; fi
+comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
 
-if [[ $ANNOTATION != none ]]; then
-	comm "Intersecting the transcripts with the provided annotation in $ANNOTATION"
-	${SOFT}/intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.anno.gff
-	if [[ $? -ne 0 ]]; then error "Could not intersect the transcripts with the provided annotation. Exiting..."; fi
+comm "Intersecting the transcripts with the provided annotation in $ANNOTATION"
+snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.anno.gff
+if [[ $? -ne 0 ]]; then error "Could not intersect the transcripts with the provided annotation. Exiting..."; fi
+comm "Identified $(cat ${OUT}/transcript_assembly/ncRNA.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
 
-	comm "Consolidating intergenic and antisense transcripts predicted from ORFs and $ANNOTATION"
-	mv ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/transcript_assembly/ncRNA.orf.gff
-	${SOFT}/consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}/transcript_assembly/ncRNA.anno.gff > ${OUT}/transcript_assembly/ncRNA.gff
-	if [[ $? -ne 0 ]]; then error "Transcript consolidation failed. Exiting..."; fi
-fi
+comm "Consolidating intergenic and antisense transcripts predicted from ORFs and $ANNOTATION"
+mv ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/transcript_assembly/ncRNA.orf.gff
+snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}/transcript_assembly/ncRNA.anno.gff > ${OUT}/transcript_assembly/ncRNA.gff
+if [[ $? -ne 0 ]]; then error "Transcript consolidation failed. Exiting..."; fi
+comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts"
+
 
 cp ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/nc_rna.gff
 
@@ -224,7 +250,7 @@ mkdir ${OUT}/srna_curation
 mv ${OUT}/nc_rna.gff ${OUT}/srna_curation/raw_nc_transcripts.gff
 
 comm "dynamically thresholding transcripts that are too close to a contig's edge"
-${SOFT}/positional_thresholding.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.gff ${OUT}/srna_curation/good_nc_transcripts.gff
+snapt_positional_curation.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
 if [[ $? -ne 0 ]]; then error "Failed to remove transcripts close to contig edges. Exiting..."; fi
 cp ${OUT}/srna_curation/good_nc_transcripts.gff ${OUT}/nc_transcripts.gff
 
