different cut-offs for intergenic and antisense ncRNAs

diff --git a/bin/snapt b/bin/snapt
--- a/bin/snapt
+++ b/bin/snapt
@@ -41,7 +41,8 @@ help_message () {
 	echo "	-I INT		min insert size (default=$MIN_INSERT_VALUE)"
 	echo "	-X INT		max insert size (default=$MAX_INSERT_VALUE)"
 	echo "	-m INT		minimum sRNA size during assembly (default=$MIN_LEN)"
-	echo "	-P INT		minimum reads per bp coverage to consider for transcript assembly (default=10)"
+	echo "	--intergenic-min INT	minimum reads per bp coverage to consider for intergenic transcript assembly (default=5)"
+	echo "	--antisense-min INT	minimum reads per bp coverage to consider for antisense transcript assembly (default=10)"
 	echo ""
 	echo "	--version | -v	show current SnapT version"
 	echo "";}
@@ -70,7 +71,8 @@ MAX_INSERT_VALUE=500
 MIN_LEN=50
 THREADS=1
 LENGTH=3000
-MIN_COV=10
+MIN_ANTI_COV=10
+MIN_INTER_COV=5
 
 OUT=none
 READS1=none
@@ -81,7 +83,7 @@ DATABASE=none
 RFAM=none
 
 # load in params
-OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m:l:D:R:P: --long help,version,rfam,nr -- "$@"`
+OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m:l:D:R: --long help,version,rfam,nr,intergenic-min,antisense-min -- "$@"`
 # make sure the params are entered correctly
 if [ $? -ne 0 ]; then help_message; exit 1; fi
 
@@ -101,7 +103,8 @@ while true; do
 		-I) MIN_INSERT_VALUE=$2; shift 2;;
 		-X) MAX_INSERT_VALUE=$2; shift 2;;
 		-m) MIN_LEN=$2; shift 2;;
-		-P) MIN_COV=$2; shift 2;;
+		--intergenic-min) MIN_INTER_COV=$2; shift 2;;
+		--antisense-min) MIN_ANTI_COV=$2; shift 2;;
                 -h | --help) help_message; exit 0; shift 1;;
 		-v | --version) echo SnapT v=${VERSION}; exit 0; shift 1;;
 		--skip-refinement) refine=false; shift 1;;
@@ -208,7 +211,7 @@ if [[ $ANNOTATION == none ]]; then
 		ANNOTATION=${OUT}/prokka_annotation/genome.gff
 	else
 		comm "Running Prokka on $GENOME. This usually takes a few minutes for single genomes and a few hours for metagenomes."
-		prokka --quiet --cpus $THREADS --outdir ${OUT}/prokka_annotation --prefix genome --force $GENOME
+		prokka --quiet --cpus $THREADS --outdir ${OUT}/prokka_annotation --prefix genome --force ${OUT}/hisat2_alignment/genome.fa
 		if [[ $? -ne 0 ]]; then error "Prokka annotation failed. Exiting..."; fi
 		comm "sorting PROKKA annotation"
 		bedtools sort -i ${OUT}/prokka_annotation/genome.gff > ${OUT}/prokka_annotation/genome.sorted.gff
@@ -216,35 +219,50 @@ if [[ $ANNOTATION == none ]]; then
 		ANNOTATION=${OUT}/prokka_annotation/genome.gff
 	fi
 else
-	comm "sorting $ANNOTATION annotation to guide Stringtie"
-	bedtools sort -i $ANNOTATION > ${OUT}/sorted_annotation.gff
-	if [[ $? -ne 0 ]]; then error "Failed to sort $ANNOTATION. Exiting..."; fi
+	if [[ ! -s ${OUT}/sorted_annotation.gff ]]; then
+		comm "sorting $ANNOTATION annotation to guide Stringtie"
+		bedtools sort -i $ANNOTATION > ${OUT}/sorted_annotation.gff
+		if [[ $? -ne 0 ]]; then error "Failed to sort $ANNOTATION. Exiting..."; fi
+	fi
 	ANNOTATION=${OUT}/sorted_annotation.gff
 fi
 comm "There are a total of $(cat $ANNOTATION | wc -l) transcripts in the annotation."
 
-if [[ -s ${OUT}/transcript_assembly/raw_transcripts.gff ]]; then
-	comm "Looks like the stringtie assembly already exists in the output directory. Skipping..."
+if [[ -s ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff ]]; then
+	comm "Looks like the stringtie assembly for antisense calling already exists in the output directory. Skipping..."
 else
-	comm "Building reference-based transcripts and transcriptome expression file"
+	comm "Assembling reference-based transcripts for antisense ncRNA calls (-c ${MIN_ANTI_COV})"
 	mkdir ${OUT}/transcript_assembly
 	stringtie ${OUT}/hisat2_alignment/alignment.bam \
-		-o ${OUT}/transcript_assembly/raw_transcripts.gff \
-		-p $THREADS -m $MIN_LEN -G $ANNOTATION -c $MIN_COV
+		-o ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff \
+		-p $THREADS -m $MIN_LEN -G $ANNOTATION -c $MIN_ANTI_COV
 	if [[ $? -ne 0 ]]; then error "Stringtie transcript assembly failed. Exiting..."; fi
 fi
-comm "Assembled $(cat ${OUT}/transcript_assembly/raw_transcripts.gff | wc -l) transcripts from the alignment with Stringtie."
+comm "Assembled $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff | wc -l) transcripts from the alignment with Stringtie -c ${MIN_ANTI_COV}."
+
+
+if [[ -s ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff ]]; then
+	comm "Looks like the stringtie assembly for intergenic calling already exists in the output directory. Skipping..."
+else
+	comm "Assembling reference-based transcripts for intergenic ncRNA calls (-c ${MIN_INTER_COV})"
+	stringtie ${OUT}/hisat2_alignment/alignment.bam \
+		-o ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff \
+		-p $THREADS -m $MIN_LEN -G $ANNOTATION -c $MIN_INTER_COV
+	if [[ $? -ne 0 ]]; then error "Stringtie transcript assembly failed. Exiting..."; fi
+fi
+comm "Assembled $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff | wc -l) transcripts from the alignment with Stringtie -c ${MIN_INTER_COV}."
+
 
 ########################################################################################################
 ########################             REMOVE PROTEIN-CODING TRANSCRIPTS          ########################
 ########################################################################################################
-announcement "REMOVE PROTEIN-CODING TRANSCRIPTS"
+announcement "RUNNING PRODIGAL"
 
 if [[ -s ${OUT}/transcript_assembly/prodigal_orfs.gff ]]; then
 	comm "Looks like the Prodigal ORF predictions are already made. Skipping..."
 else
 	comm "Predicting open reading frames with Prodigal"
-	prodigal -i $GENOME -f gff -o ${OUT}/transcript_assembly/prodigal_orfs.gff -q
+	prodigal -i ${OUT}/hisat2_alignment/genome.fa -f gff -o ${OUT}/transcript_assembly/prodigal_orfs.gff -q
 	if [[ $? -ne 0 ]]; then error "PRODIGAL failed to annotate genome. Exiting..."; fi
 	comm "sorting Prodigal annotation"
 	bedtools sort -i ${OUT}/transcript_assembly/prodigal_orfs.gff > ${OUT}/transcript_assembly/prodigal_orfs.sorted.gff
@@ -253,28 +271,92 @@ else
 	mv ${OUT}/transcript_assembly/prodigal_orfs.sorted.gff ${OUT}/transcript_assembly/prodigal_orfs.gff
 fi
 ORFS=${OUT}/transcript_assembly/prodigal_orfs.gff
-comm "There are $(cat ${OUT}/transcript_assembly/prodigal_orfs.sorted.gff | wc -l) Prodigal ORFs identified."
+comm "There are $(cat ${OUT}/transcript_assembly/prodigal_orfs.gff | wc -l) Prodigal ORFs identified."
+
+
+########################################################################################################
+########################             REMOVE PROTEIN-CODING TRANSCRIPTS          ########################
+########################################################################################################
+announcement "REMOVE PROTEIN-CODING TRANSCRIPTS"
+# Note to reader: the stringtie assembly was done with 2 different minimum read pileup parameters.
+# The ncRNA selection steps has to be done twice (for each stringtie assembly), and then joined at the very end.
+
 
 if [[ -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then
 	comm "Looks like intersecting the transcripts with the annotation and ORFs was already done. Skipping..."
 else
 	comm "Intersecting the transcripts with the ORFs found with Prodigal to remove transcripts that are from coding regions"
-	snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.orf.gff
-	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.orf.gff ]]; then error "Could not intersect the transcripts with the ORFs. Exiting..."; fi
-	comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts.gff | wc -l) assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.orf.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
+
+	snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff\
+	 > ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.orf.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.orf.gff ]]; then 
+		error "Could not intersect the transcripts with the ORFs. Exiting..."
+	else
+		comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff | wc -l) -c ${MIN_ANTI_COV} assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.orf.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
+	fi
+	
+
+	snapt_intersect_gff.py $ORFS ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff\
+	 > ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.orf.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.orf.gff ]]; then 
+		error "Could not intersect the transcripts with the ORFs. Exiting..."
+	else
+		comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff | wc -l) -c ${MIN_INTER_COV} assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.orf.gff | wc -l) putative non-coding transcripts using the Prodigal annotation."
+	fi
+
 
 	comm "Intersecting the transcripts with the provided annotation in $ANNOTATION"
-	snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts.gff > ${OUT}/transcript_assembly/ncRNA.anno.gff
-	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.anno.gff ]]; then error "Could not intersect the transcripts with the provided annotation. Exiting..."; fi
-	comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts.gff | wc -l) assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
+	snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff\
+	 > ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.anno.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.anno.gff ]]; then
+		error "Could not intersect the transcripts with the provided annotation. Exiting..."
+	else
+		comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_ANTI_COV}.gff | wc -l) -c ${MIN_ANTI_COV} assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
+	fi
+
+
+	snapt_intersect_gff.py $ANNOTATION ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff\
+	 > ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.anno.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.anno.gff ]]; then
+		error "Could not intersect the transcripts with the provided annotation. Exiting..."
+	else
+		comm "Out of $(cat ${OUT}/transcript_assembly/raw_transcripts_${MIN_INTER_COV}.gff | wc -l) -c ${MIN_INTER_COV} assembled transcripts, identified $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.anno.gff | wc -l) putative non-coding transcripts using the $ANNOTATION annotation."
+	fi
+
 
 	comm "Consolidating intergenic and antisense transcripts predicted from ORFs and $ANNOTATION"
-	snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}/transcript_assembly/ncRNA.anno.gff > ${OUT}/transcript_assembly/ncRNA.gff
-	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.gff ]]; then error "Transcript consolidation failed. Exiting..."; fi
+	snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.orf.gff\
+	 ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.anno.gff > ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.gff ]]; then 
+		error "Transcript consolidation failed. Exiting..."
+	else
+		comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.gff | wc -l) putative -c ${MIN_ANTI_COV} non-coding transcripts"
+	fi
+
+	
+	snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.orf.gff\
+	 ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.anno.gff > ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.gff
+	if [[ ! -s ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.gff ]]; then
+		error "Transcript consolidation failed. Exiting..."
+	else
+		comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.gff | wc -l) putative -c ${MIN_INTER_COV} non-coding transcripts"
+	fi
+
+
+	comm "Selecting and combining intergenic ncRNAs identified with -c ${MIN_INTER_COV} pileup, and antisense ncRNAs identified with -c ${MIN_ANTI_COV}"
+	grep "antisense" ${OUT}/transcript_assembly/ncRNA.${MIN_ANTI_COV}.gff > ${OUT}/transcript_assembly/ncRNA.gff
+	grep "intergenic" ${OUT}/transcript_assembly/ncRNA.${MIN_INTER_COV}.gff >> ${OUT}/transcript_assembly/ncRNA.gff
+
+	comm "Sorting concatinated set"
+	sort -n -k2 -t"_" ${OUT}/transcript_assembly/ncRNA.gff > ${OUT}/transcript_assembly/ncRNA.gff.tmp
+	mv ${OUT}/transcript_assembly/ncRNA.gff.tmp ${OUT}/transcript_assembly/ncRNA.gff
+	bedtools sort -i ${OUT}/transcript_assembly/ncRNA.gff > ${OUT}/transcript_assembly/ncRNA.gff.tmp
+	if [[ $? -ne 0 ]]; then error "Failed to sort concatinated ncRNA annotation. Exiting..."; fi
+	mv ${OUT}/transcript_assembly/ncRNA.gff.tmp ${OUT}/transcript_assembly/ncRNA.gff
 fi
 
-comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts"
 cp ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/nc_rna.gff
+comm "Extracted $(cat ${OUT}/nc_rna.gff | grep antisense | wc -l) antisense and $(cat ${OUT}/nc_rna.gff | grep intergenic | wc -l) intergenic non-coding transcripts"
 
 
 ########################################################################################################
@@ -289,19 +371,19 @@ else
 	mv ${OUT}/nc_rna.gff ${OUT}/srna_curation/raw_nc_transcripts.gff
 
 	comm "re-running Prodigal on isolated transcripts to check for coding regions"
-	bedtools getfasta -s -fi $GENOME -bed ${OUT}/srna_curation/raw_nc_transcripts.gff > ${OUT}/srna_curation/raw_nc_transcripts.fa
+	bedtools getfasta -s -fi ${OUT}/hisat2_alignment/genome.fa -bed ${OUT}/srna_curation/raw_nc_transcripts.gff > ${OUT}/srna_curation/raw_nc_transcripts.fa
 	if [[ $? -ne 0 ]]; then error "Failed to extract fasta file of transcripts. Exiting..."; fi
 	prodigal -i ${OUT}/srna_curation/raw_nc_transcripts.fa -f gff -o ${OUT}/srna_curation/raw_nc_transcripts.prodigal.gff -q
 	if [[ $? -ne 0 ]]; then error "Failed to run Prodigal. Exiting..."; fi
 	
-	comm "pulling out transcripts with ORFs greater than 1/3 of their length"
+	comm "pulling out transcripts with ORFs greater than 1/2 of their length"
 	snapt_filter_by_prodigal.py ${OUT}/srna_curation/raw_nc_transcripts.prodigal.gff ${OUT}/srna_curation/raw_nc_transcripts.gff\
 	 > ${OUT}/srna_curation/raw_nc_transcripts.noorfs.gff
 	if [[ $? -ne 0 ]]; then error "Failed to filter out signifficant prodigal hits. Exiting..."; fi
 	comm "out of $(cat ${OUT}/srna_curation/raw_nc_transcripts.gff | wc -l) transcripts, $(cat ${OUT}/srna_curation/raw_nc_transcripts.noorfs.gff | wc -l) had no notable ORFs within them"
 
 	comm "dynamically thresholding transcripts that are too close to a contig's edge"
-	snapt_positional_curation.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.noorfs.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
+	snapt_positional_curation.py ${OUT}/hisat2_alignment/genome.fa ${OUT}/srna_curation/raw_nc_transcripts.noorfs.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
 	if [[ $? -ne 0 ]]; then error "Failed to remove transcripts close to contig edges. Exiting..."; fi
 
 	comm "curating ncRNA predictions by size (minimum 50bp, maximum 500bp)"
