added diamond support

diff --git a/bin/snapt b/bin/snapt
--- a/bin/snapt
+++ b/bin/snapt
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 #SBATCH
-#SBATCH --job-name=metaWRAP
+#SBATCH --job-name=SnapT
 #SBATCH --partition=lrgmem
 #SBATCH --time=72:0:0
 #SBATCH --nodes=1
-#SBATCH --ntasks-per-node=48
-#SBATCH --cpus-per-task=1
-#SBATCH --mem=800G
+#SBATCH --ntasks-per-node=1
+#SBATCH --cpus-per-task=48
+#SBATCH --mem=100G
 
 
-VERSION="0.1.1"
+VERSION="v0.2"
 echo snapt ${@}
 
 ##############################################################################################################################################################
@@ -32,6 +32,7 @@ help_message () {
 	echo "	-l INT		minimum contig length (default=1000) for ncRNA annotation"
 	echo "	-o STR          output directory"
 	echo "	-t INT		number of threads (default=1)"
+	echo "	-d STR		NCBI_nr protein database DIAMOND index (see installation instructions for details)"
 	echo ""
 	echo "Aligment options:"
 	echo "	-r STR		rna-strandness: R or F for single-end, RF or FR for paired-end (default=FR)"
@@ -72,10 +73,11 @@ READS1=none
 READS2=none
 GENOME=none
 ANNOTATION=none
+DATABASE=none
 
 
 # load in params
-OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m:l: --long help,version -- "$@"`
+OPTS=`getopt -o hvt:1:2:g:a:o:r:I:X:m:l:d: --long help,version -- "$@"`
 # make sure the params are entered correctly
 if [ $? -ne 0 ]; then help_message; exit 1; fi
 
@@ -89,6 +91,7 @@ while true; do
 		-a) ANNOTATION=$2; shift 2;;
 		-t) THREADS=$2; shift 2;;
 		-l) LENGTH=$2; shift 2;;
+		-d) DATABASE=$2; shift 2;;
 		-r) STRAND_MAP_VALUE=$2; shift 2;;
 		-I) MIN_INSERT_VALUE=$2; shift 2;;
 		-X) MAX_INSERT_VALUE=$2; shift 2;;
@@ -115,6 +118,11 @@ elif [ ! -s $GENOME ]; then
 	error "Genome/metagenome file $GENOME does not exist, or is empty. Exiting."
 fi
 
+if [[ $DATABASE == none ]]; then
+	warning "You did not specify the NCBI_nr database location with the -d option. SnapT will not be able to perform the homology search!"
+fi
+
+
 announcement "BEGIN PIPELINE!"
 comm "setting up output folder and copying relevant information..."
 if [ ! -d $OUT ]; then
@@ -131,11 +139,11 @@ fi
 ########################################################################################################
 announcement "ALIGN RNA READS TO GENOME WITH HISAT2"
 
-mkdir ${OUT}/hisat2
 if [[ -s ${OUT}/hisat2/hisat2_index.1.ht2 ]]; then
 	comm "Looks like the Hisat2 index already exists in the output directory. Skipping..."
 else
 	comm "Building Hisat2 index from reference genome"
+	mkdir ${OUT}/hisat2
 	cp $GENOME ${OUT}/hisat2/genome.fa
 	hisat2-build ${OUT}/hisat2/genome.fa ${OUT}/hisat2/hisat2_index \
 	 -p $THREADS --quiet
@@ -194,11 +202,11 @@ else
 fi
 
 
-mkdir ${OUT}/transcript_assembly
 if [[ -s ${OUT}/transcript_assembly/raw_transcripts.gff ]]; then
 	comm "Looks like the stringtie assembly already exists in the output directory. Skipping..."
 else
 	comm "Building reference-based transcripts and transcriptome expression file"
+	mkdir ${OUT}/transcript_assembly
 	stringtie ${OUT}/hisat2/alignment.bam \
 		-o ${OUT}/transcript_assembly/raw_transcripts.gff \
 		-p $THREADS -m $GAP_VALUE -G $ANNOTATION
@@ -237,7 +245,6 @@ snapt_consolidate_transcripts.py ${OUT}/transcript_assembly/ncRNA.orf.gff ${OUT}
 if [[ $? -ne 0 ]]; then error "Transcript consolidation failed. Exiting..."; fi
 comm "Filtered down to $(cat ${OUT}/transcript_assembly/ncRNA.gff | wc -l) putative non-coding transcripts"
 
-
 cp ${OUT}/transcript_assembly/ncRNA.gff ${OUT}/nc_rna.gff
 
 
@@ -252,7 +259,49 @@ mv ${OUT}/nc_rna.gff ${OUT}/srna_curation/raw_nc_transcripts.gff
 comm "dynamically thresholding transcripts that are too close to a contig's edge"
 snapt_positional_curation.py $GENOME ${OUT}/srna_curation/raw_nc_transcripts.gff ${OUT}/srna_curation/good_nc_transcripts.gff $LENGTH
 if [[ $? -ne 0 ]]; then error "Failed to remove transcripts close to contig edges. Exiting..."; fi
-cp ${OUT}/srna_curation/good_nc_transcripts.gff ${OUT}/nc_transcripts.gff
+
+comm "curating ncRNA predictions by size (minimum 50bp, maximum 500bp)"
+snapt_size_select.py ${OUT}/srna_curation/good_nc_transcripts.gff 50 500 > ${OUT}/small_nc_transcripts.gff 
+if [[ $? -ne 0 ]]; then error "Failed to size select the transcripts. Exiting..."; fi
+comm "Out of $(cat ${OUT}/srna_curation/good_nc_transcripts.gff | wc -l) ncRNAs, there are $(cat ${OUT}/small_nc_transcripts.gff | wc -l) small ncRNAs, of which $(cat ${OUT}/small_nc_transcripts.gff | grep "intergenic" | wc -l) are intergenic and $(cat ${OUT}/small_nc_transcripts.gff | grep "antisense" | wc -l) are antisense."
+
+
+########################################################################################################
+########################         CROSS REFERING TRANSCRIPTS WITH BLASTX         ########################
+########################################################################################################
+if [[ $DATABASE == none ]]; then
+	announcement "NCBI_nr database not provided. Unable to use homology search to further curate small ncRNAs. You will find the final predictions in ${OUT}/small_nc_transcripts.gff. This is not ideal, but the pipeline completed successfully."
+	exit 0
+fi
+
+announcement "CROSS REFERING TRANSCRIPTS WITH BLASTX"
+
+if [[ -s ${OUT}/nr_hits.blast ]]; then
+	comm "Looks like DIAMOND Blastx was already run - ${OUT}/nr_hits.blast exists. Skipping..."
+else
+	comm "pulling out fasta file from $GENOME assembly and ${OUT}/small_nc_transcripts.gff transcripts"
+	bedtools getfasta -fi $GENOME -bed ${OUT}/small_nc_transcripts.gff > ${OUT}/small_nc_transcripts.fa
+	if [[ $? -ne 0 ]]; then error "Failed to pull out fasta file from GFF. Exiting..."; fi
+
+	# download and index the nr database:
+	# wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz
+	# gunzip nr.gz
+	# mv nr nr.faa
+	# diamond makedb --in nr.faa -d nr
+	comm "running DIAMOND blastx of ${OUT}/small_nc_transcripts.fa against the $DATABASE database"
+	diamond blastx --threads $THREADS --db $DATABASE --out ${OUT}/nr_hits.blast\
+	 --outfmt 6 qseqid sseqid bitscore pident nident qlen slen length mismatch qstart qend sstart send\
+	 --query-cover 30 --evalue 0.0001 --query ${OUT}/small_nc_transcripts.fa
+	if [[ $? -ne 0 ]]; then error "DIAMOND Blastx search against the database. Exiting..."; fi
+fi
+
+comm "filtering blastx hits for bit score > 50 and percent identity > 30"
+# Note that query cover >30% and eval < 0.0001 is already done at the alignment step
+cat ${OUT}/nr_hits.blast | awk '{ if ($3>50) print $0 }' | awk '{ if ($4>30) print $0 }' | cut -f1 | uniq | ${OUT}/nr_hits.list
+comm "Out of $(cat ${OUT}/small_nc_transcripts.gff | wc -l) small ncRNA sequences, $(cat ${OUT}/nr_hits.list | wc -l) had signifficant hits against the protein database"
+
+
+comm "pulling out small ncRNA preditions without any blastx hits to the NR database"
 
 
 ########################################################################################################
